module.exports = {
    CREATE_CAMPAIGN: "CREATE_CAMPAIGN",
    RECEIVE_ALL_CAMPAIGNS: "RECEIVE_ALL_CAMPAIGNS",
    RECEIVE_ALL_SOURCES: "RECEIVE_ALL_SOURCES",
    RECEIVE_ALL_TARGETS: "RECEIVE_ALL_TARGETS",
    CREATE_SOURCE: "CREATE_SOURCE",
    CREATE_TARGET: "CREATE_TARGET"
}